### ISSUE TITLE
Compatibility List

### ISSUE THREAD

**Issue by JeffBrownTech** [MicrosoftDocs/OfficeDocs-OfficeOnlineServer#10]
In the Compatibility List, Exchange Server 2013 is listed as "no" for both products. Is this accurate? I thought Exchange 2013 could use Office Web/Office Online to preview attachments.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8ca0ba7-ad2d-e079-813a-b4e2d622de96
* Version Independent ID: 9c5e5594-ebff-f90f-fe73-71b545c3b2e7
* Content: [Office Online Server](https://docs.microsoft.com/en-us/officeonlineserver/office-online-server)
* Content Source: [OfficeOnlineServer/office-online-server.md](https://github.com/MicrosoftDocs/OfficeDocs-OfficeOnlineServer/blob/live/OfficeOnlineServer/office-online-server.md)
* Product: **office-online-server**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by JasonH-Msft** [comment]
Exchange product team doesn't support the integration with 2013, only Exchange 2016 + OOS is supported.

**Comment by tseward** [comment]
You sure? Exchange 2013 had explicit instructions on TN for integration with OWA 2013.

**Comment by JasonH-Msft** [comment]
Affirmative.  The TN instructions should have been pulled too.

**Comment by MikePlumleyMSFT** [comment]
@dstrome can help update the Exchange article if it's still out there.

**Comment by dstrome** [comment]
I remember we pulled the topic a year or two ago. If there's still a copy out there that says Exchange 2013 works with OOS, please provide a link and I'll get it taken care of. Thanks.
