### ISSUE TITLE
Sharepoint 2013

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/OfficeDocs-OfficeOnlineServer#15]
The steps are probably the same for Sharepoint 2013 and Sharepoint 2016, but it would be nice if somewhere in the docs mentioned this. So far the only mention is on the [compatibility list on the home page](https://docs.microsoft.com/en-us/officeonlineserver/office-online-server#office-online-server-version-compatibility-list)

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9579b467-9b55-1aae-589e-4864ab028984
* Version Independent ID: f0c07ff9-52c9-d4d9-226a-e8b561de6581
* Content: [Configure Office Online Server for SharePoint Server 2016](https://docs.microsoft.com/en-us/officeonlineserver/configure-office-online-server-for-sharepoint-server-2016/configure-office-online-server-for-sharepoint-server-2016)
* Content Source: [OfficeOnlineServer/configure-office-online-server-for-sharepoint-server-2016/configure-office-online-server-for-sharepoint-server-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-OfficeOnlineServer/blob/live/OfficeOnlineServer/configure-office-online-server-for-sharepoint-server-2016/configure-office-online-server-for-sharepoint-server-2016.md)
* Product: **office-online-server**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by JasonH-Msft** [comment]
resolved with OOS deployment article updates
