### ISSUE TITLE
SharePoint 2019 support

### ISSUE THREAD

**Issue by StacyRacks** [MicrosoftDocs/OfficeDocs-OfficeOnlineServer#18]
Hi

Does OOS support SP 2019 since everything is in the 16 hive, for the most.  And, the rest is in same locations within windows file system 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8ca0ba7-ad2d-e079-813a-b4e2d622de96
* Version Independent ID: 9c5e5594-ebff-f90f-fe73-71b545c3b2e7
* Content: [Office Online Server](https://docs.microsoft.com/en-us/officeonlineserver/office-online-server#office-online-server-version-compatibility-list)
* Content Source: [OfficeOnlineServer/office-online-server.md](https://github.com/MicrosoftDocs/OfficeDocs-OfficeOnlineServer/blob/live/OfficeOnlineServer/office-online-server.md)
* Product: **office-online-server**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by tseward** [comment]
Yes, OOS fully supports 2019.

**Comment by StacyRacks** [comment]
Thanks Trevor!

**Comment by paololec** [comment]
Why if SharePoint 2019 is fully supported is not indicated in compatibility list above?
