### ISSUE TITLE
在线编辑pptx修改字体保存不了

### ISSUE THREAD

**Issue by yanweicheng** [MicrosoftDocs/OfficeDocs-OfficeOnlineServer#19]
使用的Office online server，但是使用编辑pptx的时候里面的字体确修改不了，请问下什么原因

**Comment by AndreaBarr** [comment]
@yanweicheng 感谢您的反馈。

我想快速解决有关字体问题的问题。 支持可以处理此问题以解决问题。

我认为最好的方法是，如果您可以在租户中打开服务票，这样可以尽快解决。 根据结果，让我知道它是否可以在文档中调用。
 
以下是打开机票的快速视频：https：//www.youtube.com/watch？v = puuOy0sEg1Y
 
如果你不介意，请告诉我们这里的决议，我真的希望得到你发现回到文档中的这些信息。
