### ISSUE TITLE
I found that I had to load four features from sxs directories (side-by-side)

### ISSUE THREAD

**Issue by vgpaul** [MicrosoftDocs/OfficeDocs-OfficeOnlineServer#2]
Four features have to be installed using the operating system GUI and an alternate path from the DVD\ISO

D:\sources\sxs

NET-Framework-Features
NET-Framework-Core
NET-HTTP-Activation
NET-Non-HTTP-Activ

[X] .NET Framework 3.5 Features                         NET-Framework-Features         Installed
    [X] .NET Framework 3.5 (includes .NET 2.0 and 3.0)  NET-Framework-Core             Installed
    [X] HTTP Activation                                 NET-HTTP-Activation            Installed
    [X] Non-HTTP Activation                             NET-Non-HTTP-Activ             Installed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb30d62f-9a48-d8c2-a755-161611c2399f
* Version Independent ID: c7f7e286-1d24-6e60-91e2-503cd53b8c36
* [Content](https://docs.microsoft.com/en-us/officeonlineserver/deploy-office-online-server)
* [Content Source](https://github.com/MicrosoftDocs/OfficeDocs-OfficeOnlineServer/blob/live/OfficeOnlineServer/deploy-office-online-server.md)
* Service: unspecified

**Comment by lorenahuangliu** [comment]
Hi there, thank you for submitting this issue. I'll try my best to answer your questions. I am not sure I understand the question in this case, would you mind clarifying? 

Best,
Lorena | Office Online Server PM

**Comment by vgpaul** [comment]
When doing the 2016\OOS install. When I tried to do the Add-WindowsFeature line I got errors on these four features.  It took me a while to find the solution (loading through SXS) so I put it into the thread to hopefully help others.

Thanks
