### ISSUE TITLE
Office online server doesn't support tables in a word well

### ISSUE THREAD

**Issue by qquiuc** [MicrosoftDocs/OfficeDocs-OfficeOnlineServer#21]
Hi Team,

Currently I'm working with the office online server(owa 2016),

I have tried to open a office word in the office online server, and there are two tables in the document in a row, but when i open this word in the Office word online editing view, the two tables will be displayed in a column, please see the attachments.

Could you tell me if there are limitations for tables in a word?

Thanks a lot
![tablesinowa](https://user-images.githubusercontent.com/18695819/46134715-29527780-c276-11e8-892a-9d6b144d1ada.png)
![tablesinwordapp](https://user-images.githubusercontent.com/18695819/46134716-29eb0e00-c276-11e8-831c-302cddb7be40.png)
[TestDc.docx](https://github.com/MicrosoftDocs/OfficeDocs-OfficeOnlineServer/files/2423338/TestDc.docx)

**Comment by AndreaBarr** [comment]
@qquiuc Thank you for this feedback

I want to make sure we address this tables issue promptly for you. Support can handle this to resolution. 

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs. 
 
https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/130
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
