### ISSUE TITLE
another parameter for adding feature

### ISSUE THREAD

**Issue by ZakharGoncharov** [MicrosoftDocs/OfficeDocs-OfficeOnlineServer#23]
In part "To install Office Online Server on Windows Server 2012 R2" - "Add-WindowsFeature Web-Server..."
should add parameter: "-Source C:\2012r2\sources\sxs"
otherwise you will get error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb30d62f-9a48-d8c2-a755-161611c2399f
* Version Independent ID: c7f7e286-1d24-6e60-91e2-503cd53b8c36
* Content: [Deploy Office Online Server](https://docs.microsoft.com/en-us/officeonlineserver/deploy-office-online-server)
* Content Source: [OfficeOnlineServer/deploy-office-online-server.md](https://github.com/MicrosoftDocs/OfficeDocs-OfficeOnlineServer/blob/live/OfficeOnlineServer/deploy-office-online-server.md)
* Product: **office-online-server**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by JasonH-Msft** [comment]
do not change.  -Source is not a default required parameter and is only required if using a non-default custom source for OS features.
