### ISSUE TITLE
Exchange 2019 version compatibility?

### ISSUE THREAD

**Issue by m49808** [MicrosoftDocs/OfficeDocs-OfficeOnlineServer#29]
Exchange 2019 is not in the compatibility list, despite the docs for Exchange 2019 listing OOS as an optional prerequisite. Is this supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8ca0ba7-ad2d-e079-813a-b4e2d622de96
* Version Independent ID: 9c5e5594-ebff-f90f-fe73-71b545c3b2e7
* Content: [Office Online Server](https://docs.microsoft.com/en-us/OfficeOnlineServer/office-online-server)
* Content Source: [OfficeOnlineServer/office-online-server.md](https://github.com/MicrosoftDocs/OfficeDocs-OfficeOnlineServer/blob/live/OfficeOnlineServer/office-online-server.md)
* Product: **office-online-server**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by AndreaBarr** [comment]
@m49808 Thank you for this inquiry

I am not sure if Exchange 2019 is compatible. Let me get this over to the Office Online Server writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by oviwin** [comment]
Skype for Business 2019 is not in the compatibility list, despite the docs for Skype for Business 2019 listing OOS as an optional prerequisite. Is this supported?

**Comment by AndreaBarr** [comment]
@jamesrhea Could you please investigate this?

**Comment by santanu-wac** [comment]
Exchange 2019 is compatible with OOS. We have updated the OOS docs here - [https://docs.microsoft.com/en-us/OfficeOnlineServer/office-online-server](url)
