### ISSUE TITLE
This article needs updating... It is missing the update from June 2018

### ISSUE THREAD

**Issue by ScottStauffer** [MicrosoftDocs/OfficeDocs-OfficeOnlineServer#31]

**Comment by ScottStauffer** [comment]
It is also missing an update to the November 2018 that was release 6 days ago... for that matter, there is not link to the Download for November 2018!

**Comment by AndreaBarr** [comment]
@ScottStauffer What article are you referring to? You opened an issue directly to the Repo so we can't see what article you want updated.
