### ISSUE TITLE
Support for install on Server 2019?

### ISSUE THREAD

**Issue by m49808** [MicrosoftDocs/OfficeDocs-OfficeOnlineServer#32]
Is this supported for install on Server 2019 or more importantly Server 2019 Core?

**Comment by tseward** [comment]
OOS does not support Core. Not sure on Server 2019 though keep in mind with the delay of Server 2019's RTM release, testing may have been an issue.

**Comment by lorenahuangliu** [comment]
OOS does not currently have official Windows Server 2019 support.
