### ISSUE TITLE
Windows Server 2019 Support

### ISSUE THREAD

**Issue by PMSchneider** [MicrosoftDocs/OfficeDocs-OfficeOnlineServer#33]
is the "Office Online Server last updated November 2018" supporting Windows Server 2019 (current /LTSC)?
I could not find it mentioned in the Articels (only Windows2012R2 and Windows 2016).
It seems to run without resonable issues, but i need a info if or which reelase of WAC will be supported on win2019.
Thank you!

**Comment by JasonH-Msft** [comment]
no plans for Windows Server 2019 support

**Comment by berendengelbrecht** [comment]
We just installed OOS November 2018 on Windows Server 2019 and it appears to run fine.

**Comment by JasonH-Msft** [comment]
won't be supported by Microsoft

**Comment by Bravecold** [comment]
I've been setting this up, Windows Server 2019, Sharepoint 2019 and over OOS 2019 on Windows Server 2019 (without the ink and hand writing feature) and didn't work... on the installation process it looks good, but on the SharePoint 2019 portal didn't open any online document... any advise?
