### ISSUE TITLE
The note has a broken url

### ISSUE THREAD

**Issue by glawn** [MicrosoftDocs/OfficeDocs-OfficeOnlineServer#38]
Where you say:  Microsoft hosts an Internet-only facing version of Create URL on Office.com.  The link does not take you to a generate.aspx page.  It goes to a generic sales page instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2067f074-2b2e-72d5-51e5-9512f21135ce
* Version Independent ID: 8739ef49-e9bc-676f-1dde-bf98b7ab405b
* Content: [Office Online Server overview](https://docs.microsoft.com/en-us/officeonlineserver/office-online-server-overview#feedback)
* Content Source: [OfficeOnlineServer/office-online-server-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-OfficeOnlineServer/blob/live/OfficeOnlineServer/office-online-server-overview.md)
* Product: **office-online-server**
* GitHub Login: @lorenahuangliu
* Microsoft Alias: **lohuan**

**Comment by lorenahuangliu** [comment]
Thanks @glawn , I've fixed the issue now. Appreciate you submitting this.

**Comment by glawn** [comment]
Thanks for looking at this, but now it just goes to base office.com.

The text of the note and the context of the surrounding text says it should
go to the /op/generate.aspx to generate an Office Online url.




*Greg Lawn | Technical Engineer*

Greg.Lawn@Nuix.com | www.nuix.com

Phone: +1 281 778 0530 | Mobile: +1 281 216 5212

Skype: glawn01@nuix.com | Twitter: twitter.com/nuix
<http://www.twitter.com/nuix>
