### ISSUE TITLE
What about SharePoint 2019?

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-OfficeOnlineServer#43]
Please update to include SP 2019 as appropriate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9579b467-9b55-1aae-589e-4864ab028984
* Version Independent ID: f0c07ff9-52c9-d4d9-226a-e8b561de6581
* Content: [Configure Office Online Server for SharePoint Server 2016](https://docs.microsoft.com/en-us/officeonlineserver/configure-office-online-server-for-sharepoint-server-2016/configure-office-online-server-for-sharepoint-server-2016)
* Content Source: [OfficeOnlineServer/configure-office-online-server-for-sharepoint-server-2016/configure-office-online-server-for-sharepoint-server-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-OfficeOnlineServer/blob/live/OfficeOnlineServer/configure-office-online-server-for-sharepoint-server-2016/configure-office-online-server-for-sharepoint-server-2016.md)
* Product: **office-online-server**
* GitHub Login: @lorenahuangliu
* Microsoft Alias: **lohuan**

**Comment by DeanGross** [comment]
Following up, does Office Online Server support SP 2019 ?

**Comment by APetersen786** [comment]
https://social.technet.microsoft.com/wiki/contents/articles/52608.office-online-server-for-sharepoint-server-2019.aspx 
says yes. Will try it soon and see.

**Comment by santanu-wac** [comment]
SP 2019 has been updated, as applicable
