### ISSUE TITLE
Does this apply to every KB released in every month

### ISSUE THREAD

**Issue by FullStackEngN** [MicrosoftDocs/OfficeDocs-OfficeOnlineServer#45]
Generally Office will have KB released every month, it also includes Office Online Server update.
For example, https://support.microsoft.com/en-us/help/4475511/security-update-for-office-online-server-june-11-2019
and 
https://support.microsoft.com/en-us/help/4461633/description-of-the-security-update-for-office-online-server-january

They are security update for Office Online Server.
Do I need rebuild OOS farm after installing them? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7182ae01-c978-29fc-6fcf-52f60fa59aad
* Version Independent ID: e2dfe89c-59e7-8e32-ee18-e0b346527b43
* Content: [Apply software updates to Office Online Server](https://docs.microsoft.com/en-us/officeonlineserver/apply-software-updates-to-office-online-server#feedback)
* Content Source: [OfficeOnlineServer/apply-software-updates-to-office-online-server.md](https://github.com/MicrosoftDocs/OfficeDocs-OfficeOnlineServer/blob/live/OfficeOnlineServer/apply-software-updates-to-office-online-server.md)
* Product: **office-online-server**
* GitHub Login: @santanu-wac
* Microsoft Alias: **samukhe**

**Comment by tseward** [comment]
Yes, this applies to every update from Microsoft Update.

**Comment by santanu-wac** [comment]
Yes, and please follow the instructions here - [https://docs.microsoft.com/en-us/OfficeOnlineServer/apply-software-updates-to-office-online-server#apply-software-updates-or-new-versions-to-a-single-server-office-online-server-farm](url)
