### ISSUE TITLE
SharePoint 2016 & Office Web Apps server

### ISSUE THREAD

**Issue by njmathews8** [MicrosoftDocs/OfficeDocs-OfficeOnlineServer#50]
We're running a SharePoint 2016 server farm which is Office Web Apps aware so the version compatibility list is not accurate based on our experience....?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8ca0ba7-ad2d-e079-813a-b4e2d622de96
* Version Independent ID: 9c5e5594-ebff-f90f-fe73-71b545c3b2e7
* Content: [Office Online Server](https://docs.microsoft.com/en-us/officeonlineserver/office-online-server#feedback)
* Content Source: [OfficeOnlineServer/office-online-server.md](https://github.com/MicrosoftDocs/OfficeDocs-OfficeOnlineServer/blob/live/OfficeOnlineServer/office-online-server.md)
* Product: **office-online-server**
* GitHub Login: @santanu-wac
* Microsoft Alias: **samukhe**

**Comment by santanu-wac** [comment]
SharePoint 2016 server farm might be Office Web Apps aware as you pointed out, but officially there is no PG/dev support of Office Web Apps 2013 with SharePoint 2016.
