### ISSUE TITLE
Support for Windows 2019?

### ISSUE THREAD

**Issue by c3rberus** [MicrosoftDocs/OfficeDocs-OfficeOnlineServer#56]
I know this question has been asked, and the answer was that there are no plans to support this product for Windows 2019.

This sounds to me as if this product will not be maintained in the near future, I mean we have Exchange 2019 out for a year now and is RECOMMENDING to use Windows 2019.

If you try to integrate Office Online Server with Exchange 2019 on Windows 2019 you run into TLS 1.2 issues and need to apply workarounds, some of this would be resolved by default by supporting Windows 2019.

What is the reason for not supporting Windows 2019 other than "no plans"? The future looks bleak for Office Online Server if the stance is that it will not be supported.

**Comment by santanu-wac** [comment]
Office Online Server is under the Modern Lifecycle Policy and we will continue to support our release. We cannot share roadmap or future plans at the moment.
