### ISSUE TITLE
[!NOTE] Office Online Server does not support Windows Server 2019.

### ISSUE THREAD

**Issue by scott-mcallister** [MicrosoftDocs/OfficeDocs-OfficeOnlineServer#70]
Hi

I notice that this document was last updated in Jan 15, Is it still accurate that Office Online Server is not supported on Windows Server 2019? 

https://github.com/MicrosoftDocs/OfficeDocs-OfficeOnlineServer/blob/live/OfficeOnlineServer/plan-office-online-server.md

**Comment by tseward** [comment]
That's correct.
