### ISSUE TITLE
Ports

### ISSUE THREAD

**Issue by eschrader** [MicrosoftDocs/OfficeDocs-OfficeOnlineServer#8]
Can the ports be added to this article? I only see ports on technet, not docs.microsoft.com
https://social.technet.microsoft.com/wiki/contents/articles/34407.sharepoint-2016-step-by-step-installation-of-workflow-manager.aspx 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb30d62f-9a48-d8c2-a755-161611c2399f
* Version Independent ID: c7f7e286-1d24-6e60-91e2-503cd53b8c36
* Content: [Deploy Office Online Server](https://docs.microsoft.com/en-us/officeonlineserver/deploy-office-online-server)
* Content Source: [OfficeOnlineServer/deploy-office-online-server.md](https://github.com/MicrosoftDocs/OfficeDocs-OfficeOnlineServer/blob/live/OfficeOnlineServer/deploy-office-online-server.md)
* Product: **office-online-server**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by tseward** [comment]
This is documented at:

https://docs.microsoft.com/en-us/officeonlineserver/plan-office-online-server

**Comment by kenwith** [comment]
Created a Pull Request with cross link. Thanks. https://github.com/MicrosoftDocs/OfficeDocs-OfficeOnlineServer/pull/9
